const CATEGORY_META = {
  "台式餐廳":{color:"#c85d3f",ticket:300},"中式餐廳":{color:"#b94d36",ticket:420},"日式料理":{color:"#d9714d",ticket:480},"韓式料理":{color:"#db8055",ticket:420},"東南亞料理":{color:"#e19052",ticket:320},"歐美餐廳":{color:"#ad674e",ticket:520},"素食餐廳":{color:"#6f9a5a",ticket:260},"火鍋":{color:"#b74732",ticket:520},"燒烤":{color:"#8e4738",ticket:650},"健康餐盒":{color:"#639b72",ticket:180},"其他餐廳":{color:"#a96b55",ticket:320},
  "便當自助餐":{color:"#e4a33f",ticket:130},"麵食水餃":{color:"#d8943e",ticket:140},"早餐早午餐":{color:"#e9b957",ticket:150},"漢堡炸物":{color:"#dca047",ticket:180},"台灣小吃":{color:"#e0aa55",ticket:120},"宵夜滷味":{color:"#c9894a",ticket:180},"其他小吃快餐":{color:"#d6a15d",ticket:160},
  "手搖茶飲":{color:"#aa7a42",ticket:75},"咖啡廳":{color:"#795b49",ticket:160},"果汁飲品":{color:"#d78e3f",ticket:90},"茶館":{color:"#728c60",ticket:180},"酒吧餐酒館":{color:"#72506f",ticket:650},
  "豆花仙草":{color:"#c57591",ticket:70},"冰品甜湯":{color:"#8b83be",ticket:110},"蛋糕甜點":{color:"#d783a4",ticket:220},"麵包烘焙":{color:"#bc8a61",ticket:150},
  "便利超商":{color:"#3f9470",ticket:180},"超市量販":{color:"#398968",ticket:480},"食材生鮮":{color:"#67965e",ticket:350},"熟食食品":{color:"#7b8c58",ticket:220},"其他飲食":{color:"#8c918c",ticket:180}
};
const CUISINE_NAMES = { chinese:"中式",taiwanese:"台式",japanese:"日式",korean:"韓式",italian:"義式",american:"美式",burger:"漢堡",pizza:"披薩",noodle:"麵食",ramen:"拉麵",sushi:"壽司",hot_pot:"火鍋",vegetarian:"蔬食",coffee_shop:"咖啡",bubble_tea:"手搖飲",breakfast:"早餐",brunch:"早午餐",steak_house:"牛排",vietnamese:"越式",thai:"泰式",indian:"印度",bakery:"烘焙",seafood:"海鮮",chicken:"雞肉",barbecue:"燒烤" };
const SUBTYPE_OPTIONS = {
  dessert:[{id:"tofu-pudding",label:"豆花店"},{id:"ice",label:"冰品甜湯"},{id:"bakery-dessert",label:"烘焙甜點"}],
  drink:[{id:"bubble-tea",label:"手搖飲"},{id:"coffee",label:"平價咖啡"}],
  restaurant:[{id:"healthy-lunch",label:"健康便當"},{id:"hotpot",label:"火鍋"},{id:"late-night",label:"宵夜餐館"}],
  breakfast:[{id:"breakfast-shop",label:"早餐店"},{id:"brunch",label:"早午餐"}]
};
const CONCEPTS = {
  "tofu-pudding":{label:"平價豆花店",short:"豆花",icon:"豆",keywords:/豆花|仙草|甜品|甜湯|燒仙草/i,cuisines:/dessert|ice_cream/i,categories:["豆花仙草"],target:["15–24","25–34","35–44"],demand:"餐後甜點與下午消費"},
  ice:{label:"冰品甜湯店",short:"冰品",icon:"冰",keywords:/冰店|冰品|剉冰|刨冰|雪花冰|甜湯|仙草/i,cuisines:/ice_cream|dessert/i,categories:["冰品甜湯"],target:["15–24","25–34","35–44"],demand:"午後與餐後消費"},
  "bakery-dessert":{label:"烘焙甜點店",short:"甜點",icon:"甜",keywords:/甜點|蛋糕|烘焙|麵包|bakery|patisserie/i,cuisines:/bakery|dessert|cake/i,categories:["蛋糕甜點","麵包烘焙"],target:["15–24","25–34","35–44"],demand:"送禮與休閒消費"},
  "bubble-tea":{label:"平價手搖飲店",short:"手搖",icon:"飲",keywords:/茶飲|手搖|飲料|珍珠|tea|茶湯|清心|五十嵐|50嵐/i,cuisines:/bubble_tea|tea/i,categories:["手搖茶飲"],target:["15–24","25–34","35–44"],demand:"通勤與午後飲品"},
  coffee:{label:"平價咖啡店",short:"咖啡",icon:"咖",keywords:/咖啡|coffee|cafe/i,cuisines:/coffee/i,categories:["咖啡廳"],target:["25–34","35–44","45–54"],demand:"辦公與停留需求"},
  "healthy-lunch":{label:"健康便當店",short:"健康餐",icon:"餐",keywords:/健康餐|便當|餐盒|輕食|低卡|沙拉/i,cuisines:/salad|healthy|bento/i,categories:["健康餐盒","便當自助餐"],target:["25–34","35–44","45–54"],demand:"平日午餐剛需"},
  hotpot:{label:"平價火鍋店",short:"火鍋",icon:"鍋",keywords:/火鍋|鍋物|涮涮鍋/i,cuisines:/hot_pot/i,categories:["火鍋"],target:["25–34","35–44","45–54"],demand:"晚餐與聚餐"},
  "late-night":{label:"宵夜餐館",short:"宵夜",icon:"夜",keywords:/宵夜|鹽酥雞|滷味|串燒|燒烤|居酒屋/i,cuisines:/barbecue|fried_chicken/i,categories:["宵夜滷味","燒烤","酒吧餐酒館"],target:["15–24","25–34","35–44"],demand:"晚間延伸消費"},
  "breakfast-shop":{label:"平價早餐店",short:"早餐",icon:"早",keywords:/早餐|飯糰|蛋餅|豆漿|早安|晨間/i,cuisines:/breakfast/i,categories:["早餐早午餐"],target:["15–24","25–34","35–44","45–54"],demand:"通勤與居民早晨剛需"},
  brunch:{label:"早午餐店",short:"早午餐",icon:"早",keywords:/早午餐|brunch/i,cuisines:/brunch/i,categories:["早餐早午餐","咖啡廳"],target:["15–24","25–34","35–44"],demand:"假日與休閒停留"}
};
const REGION_DENSITY = {taipei:9200,"new-taipei":2100,keelung:2700,taoyuan:1900,"hsinchu-city":4400,"hsinchu-county":1500};
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const fmt = new Intl.NumberFormat("zh-TW");
const compact = new Intl.NumberFormat("zh-TW", { notation:"compact", maximumFractionDigits:1 });
const clamp = (n,min,max) => Math.max(min,Math.min(max,n));
const escapeHtml = (s="") => String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

const state = {
  center:{lat:25.07857,lon:121.57605}, address:"台北市內湖區瑞光路513巷22弄5號", radius:500,
  regionIndex:null, currentRegion:"taipei", loaded:new Map(), filters:new Map(Object.keys(CATEGORY_META).map(k=>[k,true])),
  stats:null, sources:[], map:null, mapReady:false, analysis:null, loadCount:0, zoomReloads:0,
  concept:{category:"dessert",subtype:"tofu-pudding",priceMax:100}, gapResults:[]
};

function distanceMeters(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function groupCount(items,keyFn){const m=new Map();items.forEach(x=>{const k=keyFn(x);if(k)m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function allPlaces(){return [...state.loaded.values()].flat();}
function regionMeta(id){return state.regionIndex.regions.find(r=>r.id===id);}
function pointRegion(lon,lat){return state.regionIndex.regions.filter(r=>lon>=r.bbox[0]&&lon<=r.bbox[2]&&lat>=r.bbox[1]&&lat<=r.bbox[3]).sort((a,b)=>(a.bbox[2]-a.bbox[0])*(a.bbox[3]-a.bbox[1])-(b.bbox[2]-b.bbox[0])*(b.bbox[3]-b.bbox[1]))[0]||state.regionIndex.regions[0];}
function labelRegion(label=""){const pairs=[["新竹縣","hsinchu-county"],["新竹市","hsinchu-city"],["桃園市","taoyuan"],["基隆市","keelung"],["新北市","new-taipei"],["臺北市","taipei"],["台北市","taipei"]];return pairs.find(([name])=>label.includes(name))?.[1];}
function activeConcept(){return{...CONCEPTS[state.concept.subtype],id:state.concept.subtype,priceMax:state.concept.priceMax,category:state.concept.category};}
function competitorMatch(place,concept=activeConcept()){const text=`${place.name||""} ${place.subcategory||""}`;return concept.categories.includes(place.category)&&(concept.keywords.test(text)||concept.cuisines.test(place.cuisine||""));}
function placesNear(point,radius=500,pool=allPlaces()){return pool.filter(p=>distanceMeters(point,p)<=radius);}
function localSignals(point,radius=500,pool=allPlaces()){
  const local=placesNear(point,radius,pool),counts=Object.fromEntries(groupCount(local,p=>p.category)),areaHa=Math.PI*radius**2/10000,restaurants=local.filter(p=>["主食餐廳","快餐小吃"].includes(p.group)).length,drinks=local.filter(p=>p.group==="飲料咖啡").length,desserts=local.filter(p=>p.group==="甜品烘焙").length,foodRetail=local.filter(p=>p.group==="食品零售").length,convenience=(counts["便利超商"]||0)+(counts["超市量販"]||0),office=0,transit=0,medical=0,education=0,leisure=counts["酒吧餐酒館"]||0,brands=new Set(local.map(p=>p.brand).filter(Boolean)).size,menuMix=Object.keys(counts).length,spendIndex=Math.round(clamp(92+brands*.18+menuMix*.9+(counts["歐美餐廳"]||0)*.7+(counts["日式料理"]||0)*.35,82,142)),flow=Math.round(clamp(restaurants*18+drinks*12+desserts*8+foodRetail*5+brands*2,90,24500));
  const residentialProxy=clamp(.72+(convenience+(counts["早餐早午餐"]||0)+(counts["食材生鮮"]||0))/Math.max(areaHa,1)*.05,.55,1.9),density=REGION_DENSITY[state.currentRegion]||2500,residents=Math.round(density*(Math.PI*.5*.5)*residentialProxy/50)*50;
  return{local,counts,areaHa,office,transit,restaurants,drinks,desserts,foodRetail,convenience,medical,education,leisure,spendIndex,flow,residents};
}
function targetAgeProfile(signals,concept=activeConcept()){
  const base=state.stats.ageBands,boost=clamp(signals.office/Math.max(signals.local.length,1)*1.8,0,.5),f=[1,.82,1+boost,1.15+boost,1.05+boost*.5,.9,.8],weighted=base.map((x,i)=>({label:x.label,value:x.value*f[i]})),sum=weighted.reduce((s,x)=>s+x.value,0),target=weighted.filter(x=>concept.target.includes(x.label)).reduce((s,x)=>s+x.value,0);return{share:Math.round(target/sum*100),label:`${concept.target[0].split("–")[0]}–${concept.target.at(-1).split("–").at(-1)} 歲`};
}
function conceptEvaluation(point=state.center,concept=activeConcept(),radius=state.radius,pool=allPlaces()){
  const signals=localSignals(point,radius,pool),direct=signals.local.filter(p=>competitorMatch(p,concept)).map(p=>({...p,distance:Math.round(distanceMeters(point,p))})).sort((a,b)=>a.distance-b.distance),alternatives=signals.local.filter(p=>!competitorMatch(p,concept)&&concept.categories.includes(p.category)),age=targetAgeProfile(signals,concept),density=signals.local.length/Math.max(signals.areaHa,.1),demandScore=clamp(38+Math.log1p(density)*10+signals.flow/420+signals.restaurants*.28,35,98),competitionScore=clamp(96-direct.length*10-alternatives.length*.24,25,98),pricePenalty=Math.max(0,(concept.priceMax-100)/16),affordability=Math.round(clamp(88+(signals.spendIndex-100)*.45-pricePenalty,48,98)),gapScore=Math.round(clamp(demandScore*.38+competitionScore*.3+affordability*.2+age.share*.12,25,98));
  let reason;if(direct.length===0){reason=concept.category==="breakfast"?`通勤與居民需求並存，但沒有已辨識的${concept.short}`:signals.restaurants>=8?`周邊有 ${signals.restaurants} 家餐廳與明顯人流，但沒有已辨識的${concept.short}`:`生活與人流需求存在，但沒有已辨識的${concept.short}`;}else reason=direct.length<=2?`需求密度高，同類店僅 ${direct.length} 家，仍有差異化空間`:`同類店已有 ${direct.length} 家，需靠口味、價格或時段明確區隔`;
  return{concept,signals,direct,alternatives,age,demandScore:Math.round(demandScore),competitionScore:Math.round(competitionScore),affordability,gapScore,reason};
}

function featureCollection(places){return {type:"FeatureCollection",features:places.map(p=>({type:"Feature",id:p.id,geometry:{type:"Point",coordinates:[p.lon,p.lat]},properties:{id:p.id,n:p.name,b:p.brand||"",c:p.category,g:p.group||"",s:p.subcategory||"",u:p.cuisine||"",a:p.address||"",h:p.openingHours||""}}))};}
function colorExpression(){const out=["match",["get","c"]];Object.entries(CATEGORY_META).forEach(([k,v])=>out.push(k,v.color));out.push("#81908a");return out;}
function circlePolygon(center,radius,steps=96){const coords=[];const latRad=center.lat*Math.PI/180;for(let i=0;i<=steps;i++){const a=i/steps*2*Math.PI;coords.push([center.lon+(radius*Math.cos(a))/(111320*Math.cos(latRad)),center.lat+(radius*Math.sin(a))/110540]);}return {type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[coords]}};}

function softenStyle(){const layers=state.map.getStyle().layers||[];for(const layer of layers){try{const id=layer.id.toLowerCase();if(layer.type==="background")state.map.setPaintProperty(layer.id,"background-color","#eef2ed");if(layer.type==="fill"&&/water/.test(id))state.map.setPaintProperty(layer.id,"fill-color","#b9dce0");if(layer.type==="fill"&&/building/.test(id)){state.map.setPaintProperty(layer.id,"fill-color","#deddd6");state.map.setPaintProperty(layer.id,"fill-opacity",.72);}if(layer.type==="fill"&&/(park|grass|wood|forest|landcover)/.test(id))state.map.setPaintProperty(layer.id,"fill-color","#dce9dc");if(layer.type==="line"&&/(road|street|motorway|trunk)/.test(id)){state.map.setPaintProperty(layer.id,"line-color",/motorway|trunk/.test(id)?"#e5c8ab":"#ffffff");state.map.setPaintProperty(layer.id,"line-opacity",.88);}}catch{}}
}

function initMap(){
  state.map=new maplibregl.Map({container:"map",style:"https://tiles.openfreemap.org/styles/liberty",center:[state.center.lon,state.center.lat],zoom:14.3,pitch:0,bearing:0,minZoom:7,maxZoom:19,maxBounds:[[120.72,24.30],[122.20,25.42]],dragRotate:false,touchPitch:false,fadeDuration:180,renderWorldCopies:false,attributionControl:true});
  state.map.on("styleimagemissing",e=>{if(!state.map.hasImage(e.id))state.map.addImage(e.id,{width:1,height:1,data:new Uint8Array([0,0,0,0])});});
  state.map.addControl(new maplibregl.NavigationControl({showCompass:false,visualizePitch:false}),"bottom-right");
  return new Promise(resolve=>state.map.on("load",()=>{
    state.mapReady=true;softenStyle();
    state.map.addSource("market-gaps",{type:"geojson",data:{type:"FeatureCollection",features:[]}});
    state.map.addLayer({id:"gap-halo",type:"circle",source:"market-gaps",paint:{"circle-radius":["interpolate",["linear"],["get","score"],45,15,95,34],"circle-color":["interpolate",["linear"],["get","score"],45,"#f1d6a9",70,"#edaa57",90,"#e16c3a"],"circle-opacity":["interpolate",["linear"],["zoom"],10,.14,14,.25,17,.12],"circle-blur":.45}});
    state.map.addLayer({id:"gap-hotspots",type:"circle",source:"market-gaps",minzoom:11,paint:{"circle-radius":["interpolate",["linear"],["get","score"],45,5,95,11],"circle-color":["interpolate",["linear"],["get","score"],45,"#e7bd78",70,"#eb9348",90,"#dc5f34"],"circle-opacity":.82,"circle-stroke-width":2,"circle-stroke-color":"rgba(255,255,255,.9)"}});
    state.map.addLayer({id:"gap-labels",type:"symbol",source:"market-gaps",minzoom:14,layout:{"text-field":["concat",["get","short"]," ",["to-string",["get","score"]]],"text-size":9,"text-offset":[0,1.4],"text-anchor":"top"},paint:{"text-color":"#8a4b28","text-halo-color":"rgba(255,255,255,.95)","text-halo-width":1.2}});
    state.map.addSource("analysis-zone",{type:"geojson",data:{type:"FeatureCollection",features:[]}});
    state.map.addLayer({id:"analysis-fill",type:"fill",source:"analysis-zone",filter:["==",["geometry-type"],"Polygon"],paint:{"fill-color":"#d8c3a3","fill-opacity":.075}});
    state.map.addLayer({id:"analysis-line",type:"line",source:"analysis-zone",filter:["==",["geometry-type"],"Polygon"],paint:{"line-color":"rgba(255,255,255,.9)","line-width":1.2,"line-opacity":.8}});
    state.map.addLayer({id:"site-halo",type:"circle",source:"analysis-zone",filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":19,"circle-color":"#d79c4a","circle-opacity":.14,"circle-blur":.22}});
    state.map.addLayer({id:"site-point",type:"circle",source:"analysis-zone",filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":8,"circle-color":"#17221d","circle-stroke-width":4,"circle-stroke-color":"#ffffff"}});
    for(const [id,places] of state.loaded)addRegionLayers(id,places);
    applyCategoryFilter();bindMapEvents();
    if(state.analysis)updateAnalysis({fit:false});
    resolve();
  }));
}

function addRegionLayers(id,places){
  if(!state.mapReady)return;
  const source=`poi-${id}`;if(state.map.getSource(source))return;
  state.map.addSource(source,{type:"geojson",data:featureCollection(places),cluster:true,clusterMaxZoom:16,clusterRadius:48,clusterMinPoints:3});
  state.map.addLayer({id:`cluster-halo-${id}`,type:"circle",source,filter:["has","point_count"],paint:{"circle-color":"rgba(55,65,59,.10)","circle-radius":["step",["get","point_count"],18,40,24,150,31,500,38],"circle-blur":.28}});
  state.map.addLayer({id:`cluster-${id}`,type:"circle",source,filter:["has","point_count"],paint:{"circle-color":["step",["get","point_count"],"#ffffff",40,"#f5efe5",150,"#e9dcc9",500,"#d9c4a5"],"circle-opacity":.92,"circle-radius":["step",["get","point_count"],13,40,18,150,24,500,30],"circle-stroke-width":1.5,"circle-stroke-color":"rgba(82,76,66,.25)"}});
  state.map.addLayer({id:`cluster-count-${id}`,type:"symbol",source,filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-font":["Noto Sans Regular"],"text-size":["step",["get","point_count"],10,150,11]},paint:{"text-color":"#3f4742","text-halo-color":"rgba(255,255,255,.7)","text-halo-width":.5}});
  state.map.addLayer({id:`points-${id}`,type:"circle",source,filter:["!",["has","point_count"]],paint:{"circle-color":colorExpression(),"circle-radius":["interpolate",["linear"],["zoom"],8,2,12,3.2,15,5.2,18,7],"circle-opacity":["interpolate",["linear"],["zoom"],8,.55,12,.72,15,.9],"circle-stroke-color":"rgba(255,255,255,.95)","circle-stroke-width":["interpolate",["linear"],["zoom"],10,.5,15,1.5]}});
}

async function ensureRegion(id,{quiet=false}={}){
  if(state.loaded.has(id)){state.currentRegion=id;updateRegionUI();return state.loaded.get(id);}
  const meta=regionMeta(id);if(!meta)return[];
  const cache=$("#map-cache");cache.classList.add("loading");cache.querySelector("span").textContent=`正在首次載入${meta.shortName}資料…`;
  const data=await fetch(meta.file).then(r=>{if(!r.ok)throw new Error(`${meta.name}資料載入失敗`);return r.json()});
  const places=data.places.map(p=>({id:`${id}:${p.id}`,region:id,name:p.n,brand:p.b,category:p.c,group:p.g,subcategory:p.s,cuisine:p.u,address:p.a,openingHours:p.h,lat:p.y,lon:p.x}));
  state.loaded.set(id,places);state.currentRegion=id;state.loadCount++;addRegionLayers(id,places);applyCategoryFilter();renderCategoryFilters();updateRegionUI();cache.classList.remove("loading");cache.querySelector("span").textContent=`${meta.shortName}資料已快取，縮放不重新載入`;
  if(!quiet)toast(`${meta.name} ${fmt.format(places.length)} 個點位已載入`);
  return places;
}

function updateRegionUI(){const meta=regionMeta(state.currentRegion);const loadedCount=allPlaces().length;$("#current-region").textContent=meta.shortName;$("#baseline-label").textContent=`${meta.name}飲食資料`;$("#district-pop").textContent=compact.format(meta.count);$("#district-households").textContent=compact.format(loadedCount);$("#district-workforce").textContent=`${state.zoomReloads}次`;$("#data-status").textContent=`${fmt.format(state.regionIndex.totalCount)} 個北台灣飲食店家 · 已快取 ${fmt.format(loadedCount)}`;$$('[data-region]').forEach(b=>b.classList.toggle("active",b.dataset.region===state.currentRegion));}

function bindMapEvents(){
  state.map.on("click",async e=>{const layers=["gap-hotspots",...state.loaded.keys()].flatMap(id=>id==="gap-hotspots"?[id]:[`points-${id}`,`cluster-${id}`]).filter(id=>state.map.getLayer(id));const hits=layers.length?state.map.queryRenderedFeatures(e.point,{layers}):[];const hit=hits[0];if(hit?.properties?.kind==="gap"){const p=hit.properties;new maplibregl.Popup({offset:12,maxWidth:"280px"}).setLngLat(hit.geometry.coordinates).setHTML(`<div class="gap-popup"><h4>${escapeHtml(p.label)}機會熱點 · ${p.score} 分</h4><p>${escapeHtml(p.reason)}</p><div class="popup-metrics"><div><span>同類競爭</span><strong>${p.competitors} 家</strong></div><div><span>午間人流</span><strong>${compact.format(Number(p.flow))}</strong></div><div><span>附近居民</span><strong>${compact.format(Number(p.residents))}</strong></div><div><span>消費力</span><strong>${p.spend}</strong></div></div></div>`).addTo(state.map);return;}if(hit?.properties?.cluster){const source=state.map.getSource(hit.source);source.getClusterExpansionZoom(hit.properties.cluster_id).then(zoom=>state.map.easeTo({center:hit.geometry.coordinates,zoom,duration:520}));return;}if(hit){const coords=hit.geometry.coordinates,p=hit.properties;new maplibregl.Popup({offset:10,maxWidth:"290px"}).setLngLat(coords).setHTML(businessPopupHtml({lat:coords[1],lon:coords[0]},p)).addTo(state.map);return;}state.center={lat:e.lngLat.lat,lon:e.lngLat.lng};const meta=pointRegion(e.lngLat.lng,e.lngLat.lat);await ensureRegion(meta.id);state.address=`地圖選點 ${e.lngLat.lat.toFixed(5)}, ${e.lngLat.lng.toFixed(5)}`;$("#address-input").value=state.address;updateAnalysis({fit:false});});
  state.map.on("moveend",()=>{const c=state.map.getCenter(),meta=pointRegion(c.lng,c.lat);if(state.map.getZoom()>=10&&!state.loaded.has(meta.id))ensureRegion(meta.id,{quiet:true}).catch(()=>{});});
  state.map.on("mouseenter",()=>state.map.getCanvas().style.cursor="crosshair");
}

function updateAnalysisZone({fit=true}={}){if(!state.mapReady)return;const source=state.map.getSource("analysis-zone");if(!source)return;source.setData({type:"FeatureCollection",features:[circlePolygon(state.center,state.radius),{type:"Feature",properties:{},geometry:{type:"Point",coordinates:[state.center.lon,state.center.lat]}}]});if(fit){const d=state.radius/111000;state.map.fitBounds([[state.center.lon-d*1.25,state.center.lat-d],[state.center.lon+d*1.25,state.center.lat+d]],{padding:{top:110,bottom:55,left:55,right:55},duration:650,maxZoom:18});}}

function analyze(){const nearby=allPlaces().filter(p=>distanceMeters(state.center,p)<=state.radius);state.nearby=nearby;const counts=Object.fromEntries(groupCount(nearby,p=>p.category)),total=nearby.length,areaHa=Math.PI*state.radius**2/10000,uniqueBrands=new Set(nearby.map(p=>p.brand).filter(Boolean)),named=nearby.filter(p=>!p.name.startsWith("未命名")),diversity=Object.keys(counts).length/Object.keys(CATEGORY_META).length,restaurants=nearby.filter(p=>["主食餐廳","快餐小吃"].includes(p.group)).length,drinks=nearby.filter(p=>p.group==="飲料咖啡").length,desserts=nearby.filter(p=>p.group==="甜品烘焙").length,foodRetail=nearby.filter(p=>p.group==="食品零售").length,convenience=(counts["便利超商"]||0)+(counts["超市量販"]||0),office=0,transit=0,medical=0,education=0,leisure=counts["酒吧餐酒館"]||0,density=total/Math.max(areaHa,.01),spendIndex=Math.round(clamp(92+uniqueBrands.size*.18+Object.keys(counts).length*.9+(counts["歐美餐廳"]||0)*.7+(counts["日式料理"]||0)*.35,82,142)),lunchFlow=Math.round(clamp(restaurants*18+drinks*12+desserts*8+foodRetail*5+uniqueBrands.size*2,90,24500)),weekendRatio=clamp(.48+(desserts+drinks+foodRetail)/Math.max(20,restaurants)*.32,.38,1.08),demand=Math.round(clamp(40+Math.log1p(density)*12+lunchFlow/650,30,96)),access=Math.round(clamp(48+convenience*1.2+Math.min(density*2.2,25)+Math.min(state.radius/100,8),35,96)),complement=Math.round(clamp(42+diversity*58+Math.min(desserts+drinks,16),35,95)),spending=Math.round(clamp((spendIndex-75)*1.35,35,95)),competition=Math.round(clamp(92-restaurants/Math.max(total,1)*38-drinks/Math.max(total,1)*24+diversity*13,35,93)),resilience=Math.round(clamp(42+weekendRatio*40+foodRetail*.35,35,93)),score=Math.round(demand*.24+access*.17+complement*.14+spending*.18+competition*.12+resilience*.15),confidence=Math.round(clamp(58+Math.log1p(total)*5+named.length/Math.max(total,1)*12,58,92));return{counts,total,areaHa,uniqueBrands,named,density,office,transit,restaurants,drinks,desserts,foodRetail,convenience,medical,leisure,education,diversity,spendIndex,lunchFlow,weekendRatio,score,confidence,components:{demand,access,complement,spending,competition,resilience}};}

function marketGapsAtCurrent(){return Object.entries(CONCEPTS).map(([id,c])=>conceptEvaluation(state.center,{...c,id,priceMax:id===state.concept.subtype?state.concept.priceMax:(id.includes("hotpot")?400:200)},state.radius)).sort((a,b)=>b.gapScore-a.gapScore);}
function renderMarketHotspots(){
  if(!state.mapReady)return;
  const source=state.map.getSource("market-gaps");if(!source)return;
  const concept=activeConcept(),regionPlaces=state.loaded.get(state.currentRegion)||[],pool=regionPlaces.filter(p=>distanceMeters(state.center,p)<=3200),features=[];
  for(let y=-1800;y<=1800;y+=450)for(let x=-1800;x<=1800;x+=450){if(Math.hypot(x,y)>2100)continue;const point={lat:state.center.lat+y/110540,lon:state.center.lon+x/(111320*Math.cos(state.center.lat*Math.PI/180))},ev=conceptEvaluation(point,concept,450,pool);if(ev.signals.local.length<8||ev.gapScore<48)continue;features.push({type:"Feature",properties:{kind:"gap",score:ev.gapScore,short:concept.short,label:concept.label,competitors:ev.direct.length,flow:ev.signals.flow,residents:ev.signals.residents,spend:ev.signals.spendIndex,reason:ev.reason},geometry:{type:"Point",coordinates:[point.lon,point.lat]}});}
  features.sort((a,b)=>b.properties.score-a.properties.score);source.setData({type:"FeatureCollection",features:features.slice(0,24)});
}
function businessPopupHtml(point,p){const signals=localSignals(point,500),age=targetAgeProfile(signals),sameCategory=signals.local.filter(x=>x.category===p.c).length;return`<div class="business-popup"><h4>${escapeHtml(p.n)}</h4><span class="popup-category">${escapeHtml(p.c)}</span><p class="popup-sub">${p.a?escapeHtml(p.a):"地址未標註"}</p><div class="popup-metrics"><div><span>附近居民</span><strong>約 ${compact.format(signals.residents)}</strong></div><div><span>午間人流</span><strong>${compact.format(signals.flow)}</strong></div><div><span>消費力指數</span><strong>${signals.spendIndex}</strong></div><div><span>500m 內${escapeHtml(p.c)}</span><strong>${sameCategory} 家</strong></div></div><div class="popup-foot">500m 模型估算 · 核心客群 ${age.label} 約 ${age.share}%</div></div>`;}
function renderConceptComparison(baseAnalysis){
  const ev=conceptEvaluation(),concept=ev.concept,context500=localSignals(state.center,500),fit=Math.round(baseAnalysis.score*.42+ev.gapScore*.58),priceLabel=state.concept.priceMax<=100?"100 元以下":`${state.concept.priceMax} 元以下`;
  $("#evaluation-score-title").textContent=`${concept.short}適配分數`;$("#site-score").textContent=fit;$("#score-ring").style.setProperty("--score",fit);$("#concept-current-label").textContent=`${concept.label} · ${priceLabel}`;
  $("#concept-result-title").textContent=concept.label;$("#concept-result-copy").textContent=ev.reason;$("#concept-fit-score").textContent=fit;$("#concept-fit-meter").style.setProperty("--width",`${fit}%`);$(".concept-icon").textContent=concept.icon;
  $("#direct-competitors").textContent=`${ev.direct.length} 家`;$("#affordability-score").textContent=ev.affordability;$("#affordability-label").textContent=ev.affordability>=82?"多數客群可負擔":ev.affordability>=68?"價格帶可接受":"需降低價格風險";$("#resident-estimate").textContent=compact.format(context500.residents);$("#target-age-share").textContent=`${ev.age.share}%`;$("#target-age-label").textContent=ev.age.label;
  $("#competitor-list").innerHTML=ev.direct.length?ev.direct.slice(0,8).map((p,i)=>`<div class="competitor-row"><span class="competitor-rank">${i+1}</span><div><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.address||p.subcategory||"同類店家")}</span></div><b>${p.distance}m</b></div>`).join(""):`<div class="empty-competitors">此半徑內沒有辨識到直接競爭者。若周邊人流與餐飲密度高，這通常是值得現場驗證的供給空缺。</div>`;
  const gaps=marketGapsAtCurrent();state.gapResults=gaps;$("#market-gap-list").innerHTML=gaps.map(g=>`<div class="gap-row"><div><strong>${g.concept.label}</strong><p>${g.reason}</p><div class="gap-track"><i style="--width:${g.gapScore}%"></i></div></div><b>${g.gapScore}</b></div>`).join("");
  const verdict=$("#verdict"),strong=fit>=78,medium=fit>=64;verdict.classList.toggle("caution",!strong);verdict.innerHTML=`<span class="verdict-icon">${strong?"↗":medium?"→":"!"}</span><div><strong>${strong?`${concept.label}有明顯機會`:medium?`${concept.label}可條件式切入`:`${concept.label}競爭壓力偏高`}</strong><p>${ev.reason}；消費能力 ${ev.affordability} 分，核心年齡占 ${ev.age.share}%。</p></div>`;
  renderMarketHotspots();
}
function renderCategoryFilters(){const places=allPlaces(),totals=Object.fromEntries(groupCount(places,p=>p.category)),catGroup=new Map(places.map(p=>[p.category,p.group||"其他飲食"])),order=["主食餐廳","快餐小吃","飲料咖啡","甜品烘焙","食品零售","其他飲食"];$("#category-filters").innerHTML=order.map(group=>{const items=Object.entries(CATEGORY_META).filter(([n])=>totals[n]&&catGroup.get(n)===group).sort((a,b)=>totals[b[0]]-totals[a[0]]);if(!items.length)return"";const count=items.reduce((s,[n])=>s+totals[n],0);return`<div class="filter-group"><div class="filter-group-title"><span>${group}</span><b>${fmt.format(count)}</b></div><div class="filter-group-grid">${items.map(([n,m])=>`<button class="filter-chip ${state.filters.get(n)?"":"off"}" data-category="${n}" style="--chip:${m.color}" title="點一下顯示或隱藏；雙擊只看此分類"><span class="swatch"></span><span>${n}</span><span class="filter-count">${fmt.format(totals[n])}</span></button>`).join("")}</div></div>`}).join("");}
function renderCategoryBars(a){const entries=Object.entries(a.counts).sort((x,y)=>y[1]-x[1]).slice(0,6),max=entries[0]?.[1]||1;$("#category-bars").innerHTML=entries.length?entries.map(([n,c])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="--width:${c/max*100}%;--bar:${CATEGORY_META[n]?.color||"#718078"}"></div></div><b>${c}</b></div>`).join(""):`<p class="method-note" style="margin:0">此半徑尚無已收錄點位，請放大範圍。</p>`;}
function opportunityModel(a){const per100=n=>(a.counts[n]||0)/Math.max(a.total,1)*100;return[{name:"健康快速午餐",score:72+a.restaurants*.32-per100("健康餐盒")*3.2,why:"既有正餐聚落代表用餐需求，健康餐盒占比仍低時具空缺"},{name:"豆花／平價甜品",score:70+a.restaurants*.38+a.drinks*.12-per100("豆花仙草")*3.8-per100("冰品甜湯")*1.4,why:"餐後甜品可承接正餐人流，需避開甜品已過度集中的街段"},{name:"精品咖啡／外帶",score:66+a.restaurants*.22+a.desserts*.18-per100("咖啡廳")*2.6,why:"正餐與甜品聚落可疊加下午、等候與外帶場景"},{name:"早餐早午餐",score:68+a.convenience*.7+a.foodRetail*.12-per100("早餐早午餐")*2.8,why:"生活採買密度可支撐晨間固定回訪與週末早午餐"},{name:"宵夜滷味／串燒",score:60+a.restaurants*.2+a.leisure*1.1-per100("宵夜滷味")*3.1-per100("燒烤")*1.2,why:"晚餐聚落與酒吧餐酒館可延伸夜間消費"}].map(x=>({...x,score:Math.round(clamp(x.score,38,96))})).sort((x,y)=>y.score-x.score).slice(0,3);}
function renderOpportunities(a){$("#opportunity-list").innerHTML=opportunityModel(a).map((x,i)=>`<div class="opportunity"><span class="opportunity-rank">0${i+1}</span><div><strong>${x.name}</strong><span>${x.why}</span></div><span class="opportunity-score">${x.score}</span></div>`).join("");}
function renderCategoryTable(a){$("#category-table").innerHTML=Object.entries(a.counts).sort((x,y)=>y[1]-x[1]).slice(0,12).map(([n,c])=>{const d=c/Math.max(a.areaHa,.1),l=d>2.2?["高","high"]:d>.8?["中","medium"]:["低","low"],t=CATEGORY_META[n]?.ticket||0;return`<div class="table-row"><span class="cat-name">${n}</span><b>${c}</b><span>${t?`$${fmt.format(t)}`:"—"}</span><span class="comp-level ${l[1]}">${l[0]}</span></div>`}).join("")||`<div class="table-row"><span>無已收錄店家</span></div>`;}
function renderCuisine(){const cuisines=groupCount(state.nearby.flatMap(p=>(p.cuisine||"").split(/[;,]/).filter(Boolean).map(c=>({c:c.trim()}))),x=>x.c);$("#cuisine-tags").innerHTML=cuisines.length?cuisines.slice(0,14).map(([n,c])=>`<span>${CUISINE_NAMES[n]||n}<b>${c}</b></span>`).join(""):`<span>未標註口味</span>`;}
function renderPeople(a){const quickMeal=a.restaurants>a.foodRetail*.8,residential=a.convenience+a.foodRetail>a.restaurants*.45;$("#persona-title").textContent=quickMeal&&!residential?"效率導向的外食客群":residential?"穩定回訪的生活型客群":"正餐、飲品與甜品混合客群";$("#persona-copy").textContent=quickMeal&&!residential?"重視出餐速度、可預期品質與行動支付；午餐決策半徑短，下午有咖啡與飲品需求。":residential?"重視便利、信任與固定回訪；早餐、晚餐與日常採買比單一午間尖峰更穩定。":"多種餐飲需求並存，可用早餐、午餐、下午茶與晚間服務分散單一時段風險。";$("#persona-chips").innerHTML=(quickMeal&&!residential?["25–44 歲核心","重視效率","行動支付","外送接受度高"]:["生活型消費","熟客關係","晚間需求","週末仍有流量"]).map(x=>`<span>${x}</span>`).join("");const base=state.stats.ageBands,boost=clamp(a.restaurants/Math.max(a.total,1)*.45,0,.35),f=[1,.86,1+boost,1.15+boost,1.04+boost*.4,.9,.82],adj=base.map((x,i)=>({label:x.label,value:x.value*f[i]})),sum=adj.reduce((s,x)=>s+x.value,0),ages=adj.map(x=>({label:x.label,pct:x.value/sum*100})),max=Math.max(...ages.map(x=>x.pct));$("#age-chart").innerHTML=ages.map(x=>`<div class="age-bar" style="--height:${x.pct/max*100}%"><i></i><b>${x.pct.toFixed(0)}%</b><span>${x.label}</span></div>`).join("");}
function renderFlow(a){const of=clamp(a.office/Math.max(a.areaHa,1),0,10),rf=clamp((a.convenience+a.medical+a.education)/Math.max(a.areaHa,1),0,9),raw=[.12+rf*.008,.18,.48+of*.025,.72+of*.02,.46,.58,1,.78,.53,.49,.62+of*.015,.83+of*.015,.71,.49+rf*.018,.35+rf*.02,.2],flow=raw.map((v,i)=>({hour:i+6,value:Math.round(a.lunchFlow*clamp(v,.12,1.08))})),max=Math.max(...flow.map(x=>x.value));$("#flow-chart").innerHTML=flow.map(x=>`<div class="flow-column ${x.value>max*.82?"peak":""}" style="--height:${x.value/max*100}%"><i></i>${x.hour%2===0?`<span>${x.hour}</span>`:""}</div>`).join("");const events=[["08:00","通勤進場",flow.find(x=>x.hour===8).value],["12:00","午餐尖峰",flow.find(x=>x.hour===12).value],["18:00","下班移動",flow.find(x=>x.hour===18).value]];$("#flow-events").innerHTML=events.map(x=>`<div class="flow-event"><time>${x[0]}</time><div><strong>${x[1]}</strong><span>周邊業態加權推估</span></div><b>${compact.format(x[2])}</b></div>`).join("");const w=Math.round(a.weekendRatio*100);$("#day-compare").innerHTML=`<div class="day-row"><span>平日</span><div class="day-track"><div class="day-fill" style="--width:100%"></div></div><b>100</b></div><div class="day-row weekend"><span>假日</span><div class="day-track"><div class="day-fill" style="--width:${w}%"></div></div><b>${w}</b></div>`;}
function renderAdvice(a){const labels={demand:"需求密度",access:"交通可達",complement:"業態互補",spending:"消費能力",competition:"競爭餘裕",resilience:"時段韌性"};$("#score-breakdown").innerHTML=Object.entries(a.components).map(([k,v])=>`<div class="score-line ${v<55?"low":""}"><span>${labels[k]}</span><div class="line-track"><i style="--width:${v}%"></i></div><b>${v}</b></div>`).join("");const top=opportunityModel(a)[0],items=[["good","+",`優先測試「${top.name}」`,`${top.why}；建議先以快閃或外送熱區驗證。`],[a.weekendRatio<.62?"warn":"good",a.weekendRatio<.62?"!":"+",a.weekendRatio<.62?"控制週末固定成本":"週間流量較均衡",a.weekendRatio<.62?"商辦型商圈假日落差較大，排班與營業時間要能縮放。":"生活服務與休閒設施可降低只靠平日午餐的風險。"],["good","✓","簽約前做 3 日現場計數","至少觀察週二、週五與週六的 08:00、12:00、18:00，每次 30 分鐘。"]];$("#advice-list").innerHTML=items.map(x=>`<div class="advice-item ${x[0]}"><span class="advice-icon">${x[1]}</span><div><strong>${x[2]}</strong><p>${x[3]}</p></div></div>`).join("");}
function renderSummary(a){$("#selected-address").textContent=state.address;$("#site-score").textContent=a.score;$("#score-ring").style.setProperty("--score",a.score);$("#confidence-score").textContent=`${a.confidence}%`;$("#poi-count").textContent=fmt.format(a.total);$("#poi-density").textContent=`${a.density.toFixed(1)} 家／公頃`;$("#brand-count").textContent=fmt.format(a.uniqueBrands.size);$("#brand-ratio").textContent=`連鎖辨識率 ${Math.round(a.uniqueBrands.size/Math.max(a.total,1)*100)}%`;$("#spend-index").textContent=a.spendIndex;$("#lunch-flow").textContent=compact.format(a.lunchFlow);const good=a.score>=72;$("#verdict").classList.toggle("caution",!good);$("#verdict").innerHTML=`<span class="verdict-icon">${good?"↗":"!"}</span><div><strong>${good?"值得進一步評估":"條件式可行"}</strong><p>${a.office>a.convenience?"午間剛需強，晚間與假日需靠目的型消費補足。":"生活型需求較穩定，仍需核對租金與街邊可見度。"}</p></div>`;}
function renderAll(a){state.analysis=a;renderSummary(a);renderCategoryBars(a);renderOpportunities(a);renderCategoryTable(a);renderCuisine();renderPeople(a);renderFlow(a);renderAdvice(a);renderCategoryFilters();renderConceptComparison(a);}
function updateAnalysis(options={}){const a=analyze();renderAll(a);updateAnalysisZone(options);$("#walk-time").textContent=`${Math.max(1,Math.round(state.radius/80))} 分鐘`;}

async function geocodeAddress(address){const normalized=(address.includes("台")||address.includes("臺")?address:`${regionMeta(state.currentRegion).name} ${address}`).replace(/^台北/,"臺北"),lookup=async q=>{const u=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=tw&accept-language=zh-TW&q=${encodeURIComponent(q)}`,r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error("地址服務暫時無法使用");return r.json()};let data=await lookup(normalized);if(!data.length){const f=normalized.replace(/\d+弄.*$/,"").replace(/\d+號.*$/,"");if(f!==normalized){await new Promise(r=>setTimeout(r,1050));data=await lookup(f);}}if(!data.length)throw new Error("找不到這個地址，請改用附近路名或直接點地圖");const lat=Number(data[0].lat),lon=Number(data[0].lon),id=labelRegion(data[0].display_name)||pointRegion(lon,lat)?.id;if(!id||lon<120.72||lon>122.2||lat<24.3||lat>25.42)throw new Error("目前支援台北、新北、基隆、桃園與新竹");return{lat,lon,id,label:data[0].display_name};}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400);}
function renderSources(){$("#sources-list").innerHTML=state.sources.map(s=>`<div class="source-row"><div><strong>${s.name}</strong><p>${s.owner} · ${s.frequency} · 用於${s.usage}</p><a href="${s.url}" target="_blank" rel="noopener">開啟原始資料 ↗</a></div><span class="source-badge ${s.kind==="官方統計"?"official":s.kind==="實際觀測"?"observed":"model"}">${s.kind}</span></div>`).join("");}

function applyCategoryFilter(){const activeNames=[...state.filters].filter(([,v])=>v).map(([k])=>k),active=new Set(activeNames);let visible=0;for(const [id,places] of state.loaded){const filtered=places.filter(p=>active.has(p.category));visible+=filtered.length;if(state.mapReady){const source=state.map.getSource(`poi-${id}`);if(source)source.setData(featureCollection(filtered));}}const cache=$("#map-cache span");if(cache){if(activeNames.length===0)cache.textContent="所有店家圖層已隱藏";else if(activeNames.length===1)cache.textContent=`只顯示 ${activeNames[0]} · ${fmt.format(visible)} 個點位`;else cache.textContent=`${regionMeta(state.currentRegion).shortName}資料已快取，縮放不重新載入`;}}
function populateSubtypes(category,selected){const options=SUBTYPE_OPTIONS[category]||SUBTYPE_OPTIONS.dessert;$("#concept-subtype").innerHTML=options.map(x=>`<option value="${x.id}" ${x.id===selected?"selected":""}>${x.label}</option>`).join("");}
function bindEvents(){
  $("#address-form").addEventListener("submit",async e=>{e.preventDefault();const address=$("#address-input").value.trim();if(!address)return;const b=e.currentTarget.querySelector("button");b.textContent="…";try{const r=await geocodeAddress(address);state.center={lat:r.lat,lon:r.lon};state.address=address;await ensureRegion(r.id);updateAnalysis();toast("已完成地址周邊分析");}catch(err){toast(err.message)}finally{b.textContent="→"}});
  $(".quick-addresses").addEventListener("click",async e=>{const b=e.target.closest("button[data-region]");if(!b)return;state.center={lat:Number(b.dataset.lat),lon:Number(b.dataset.lon)};state.address=b.dataset.address;$("#address-input").value=state.address;await ensureRegion(b.dataset.region);updateAnalysis();});
  $(".radius-options").addEventListener("click",e=>{const b=e.target.closest("button[data-radius]");if(!b)return;state.radius=Number(b.dataset.radius);$$('.radius-options button').forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-checked",x===b?"true":"false")});updateAnalysis();});
  $("#category-filters").addEventListener("click",e=>{const b=e.target.closest("button[data-category]");if(!b)return;state.filters.set(b.dataset.category,!state.filters.get(b.dataset.category));renderCategoryFilters();applyCategoryFilter();});
  $("#category-filters").addEventListener("dblclick",e=>{const b=e.target.closest("button[data-category]");if(!b)return;state.filters.forEach((_,k)=>state.filters.set(k,k===b.dataset.category));renderCategoryFilters();applyCategoryFilter();toast(`地圖只顯示${b.dataset.category}`);});
  $("#toggle-all").addEventListener("click",e=>{const on=[...state.filters.values()].some(Boolean);state.filters.forEach((_,k)=>state.filters.set(k,!on));e.currentTarget.textContent=on?"全部顯示":"全部隱藏";renderCategoryFilters();applyCategoryFilter();});
  $("#concept-category").addEventListener("change",e=>populateSubtypes(e.target.value));
  $("#run-concept").addEventListener("click",()=>{state.concept={category:$("#concept-category").value,subtype:$("#concept-subtype").value,priceMax:Number($("#concept-price").value)};updateAnalysis({fit:false});const tab=$('[data-tab="compare"]');$$('.tabs button').forEach(x=>x.classList.toggle("active",x===tab));$$('.tab-panel').forEach(x=>x.classList.toggle("active",x.id==="tab-compare"));toast(`${activeConcept().label}評比完成`);});
  $(".tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-tab]");if(!b)return;$$('.tabs button').forEach(x=>x.classList.toggle("active",x===b));$$('.tab-panel').forEach(x=>x.classList.toggle("active",x.id===`tab-${b.dataset.tab}`));});
  $("#reset-view").addEventListener("click",()=>updateAnalysisZone({fit:true}));
  $("#locate-button").addEventListener("click",()=>{if(!navigator.geolocation)return toast("此瀏覽器不支援定位");navigator.geolocation.getCurrentPosition(async p=>{state.center={lat:p.coords.latitude,lon:p.coords.longitude};const r=pointRegion(state.center.lon,state.center.lat);await ensureRegion(r.id);state.address="目前位置";$("#address-input").value=state.address;updateAnalysis();},()=>toast("無法取得目前位置，請改用地址或地圖選點"));});
  const sd=$("#sources-dialog"),hd=$("#help-dialog");$("#open-sources").addEventListener("click",()=>sd.showModal());$("#help-button").addEventListener("click",()=>hd.showModal());$$('dialog .dialog-close').forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$$('dialog').forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));
  $("#export-button").addEventListener("click",()=>{const a=state.analysis,report={product:"北台灣餐飲選址雷達",generatedAt:new Date().toISOString(),region:regionMeta(state.currentRegion).name,address:state.address,coordinates:state.center,radiusMeters:state.radius,score:a.score,confidence:a.confidence,nearbyFoodBusinesses:a.total,brandCount:a.uniqueBrands.size,spendingIndex:a.spendIndex,estimatedLunchFlow:a.lunchFlow,categories:a.counts,opportunities:opportunityModel(a),disclaimer:"模型初篩，不構成營收或投資保證。"},blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json;charset=utf-8"}),u=URL.createObjectURL(blob),link=document.createElement("a");link.href=u;link.download=`北台灣餐飲選址-${state.radius}m-分析.json`;link.click();URL.revokeObjectURL(u);toast("分析摘要已匯出")});
}

async function boot(){try{const [index,stats,sources]=await Promise.all([fetch("./data/regions/index.json").then(r=>r.json()),fetch("./data/neihu-stats.json").then(r=>r.json()),fetch("./data/sources.json").then(r=>r.json())]);state.regionIndex=index;state.stats=stats;state.sources=sources;initMap();await ensureRegion("taipei",{quiet:true});renderSources();bindEvents();updateAnalysis();}catch(err){console.error(err);$("#data-status").textContent="資料載入失敗";toast(`載入失敗：${err.message}`);}}
boot();
