const CATEGORY_META = {
  "餐飲": { color: "#e76f3d", ticket: 260 }, "飲料咖啡": { color: "#b8793e", ticket: 95 },
  "便利零售": { color: "#2b8c68", ticket: 180 }, "醫療健康": { color: "#4778c8", ticket: 650 },
  "服飾美妝": { color: "#c15f8e", ticket: 980 }, "3C通訊": { color: "#8669c9", ticket: 3200 },
  "運動娛樂": { color: "#d49232", ticket: 720 }, "教育學習": { color: "#6f93b8", ticket: 380 },
  "金融服務": { color: "#526c89", ticket: 0 }, "交通汽車": { color: "#68766e", ticket: 850 },
  "公司辦公": { color: "#176b4d", ticket: 0 }, "交通節點": { color: "#20928b", ticket: 0 },
  "觀光休閒": { color: "#79a948", ticket: 220 }, "其他零售": { color: "#9b7562", ticket: 420 },
  "生活服務": { color: "#718078", ticket: 360 }, "其他設施": { color: "#929b96", ticket: 0 }
};
const CUISINE_NAMES = { chinese:"中式",taiwanese:"台式",japanese:"日式",korean:"韓式",italian:"義式",american:"美式",burger:"漢堡",pizza:"披薩",noodle:"麵食",ramen:"拉麵",sushi:"壽司",hot_pot:"火鍋",vegetarian:"蔬食",coffee_shop:"咖啡",bubble_tea:"手搖飲",breakfast:"早餐",brunch:"早午餐",steak_house:"牛排",vietnamese:"越式",thai:"泰式",indian:"印度",bakery:"烘焙",seafood:"海鮮",chicken:"雞肉",barbecue:"燒烤" };
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const fmt = new Intl.NumberFormat("zh-TW");
const compact = new Intl.NumberFormat("zh-TW", { notation:"compact", maximumFractionDigits:1 });
const clamp = (n,min,max) => Math.max(min,Math.min(max,n));
const escapeHtml = (s="") => String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

const state = {
  center:{lat:25.07857,lon:121.57605}, address:"台北市內湖區瑞光路513巷22弄5號", radius:500,
  regionIndex:null, currentRegion:"taipei", loaded:new Map(), filters:new Map(Object.keys(CATEGORY_META).map(k=>[k,true])),
  stats:null, sources:[], map:null, mapReady:false, analysis:null, loadCount:0, zoomReloads:0
};

function distanceMeters(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function groupCount(items,keyFn){const m=new Map();items.forEach(x=>{const k=keyFn(x);if(k)m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function allPlaces(){return [...state.loaded.values()].flat();}
function regionMeta(id){return state.regionIndex.regions.find(r=>r.id===id);}
function pointRegion(lon,lat){return state.regionIndex.regions.filter(r=>lon>=r.bbox[0]&&lon<=r.bbox[2]&&lat>=r.bbox[1]&&lat<=r.bbox[3]).sort((a,b)=>(a.bbox[2]-a.bbox[0])*(a.bbox[3]-a.bbox[1])-(b.bbox[2]-b.bbox[0])*(b.bbox[3]-b.bbox[1]))[0]||state.regionIndex.regions[0];}
function labelRegion(label=""){const pairs=[["新竹縣","hsinchu-county"],["新竹市","hsinchu-city"],["桃園市","taoyuan"],["基隆市","keelung"],["新北市","new-taipei"],["臺北市","taipei"],["台北市","taipei"]];return pairs.find(([name])=>label.includes(name))?.[1];}

function featureCollection(places){return {type:"FeatureCollection",features:places.map(p=>({type:"Feature",id:p.id,geometry:{type:"Point",coordinates:[p.lon,p.lat]},properties:{id:p.id,n:p.name,b:p.brand||"",c:p.category,s:p.subcategory||"",u:p.cuisine||"",a:p.address||"",h:p.openingHours||""}}))};}
function colorExpression(){const out=["match",["get","c"]];Object.entries(CATEGORY_META).forEach(([k,v])=>out.push(k,v.color));out.push("#81908a");return out;}
function circlePolygon(center,radius,steps=96){const coords=[];const latRad=center.lat*Math.PI/180;for(let i=0;i<=steps;i++){const a=i/steps*2*Math.PI;coords.push([center.lon+(radius*Math.cos(a))/(111320*Math.cos(latRad)),center.lat+(radius*Math.sin(a))/110540]);}return {type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[coords]}};}

function softenStyle(){const layers=state.map.getStyle().layers||[];for(const layer of layers){try{const id=layer.id.toLowerCase();if(layer.type==="background")state.map.setPaintProperty(layer.id,"background-color","#eef2ed");if(layer.type==="fill"&&/water/.test(id))state.map.setPaintProperty(layer.id,"fill-color","#b9dce0");if(layer.type==="fill"&&/building/.test(id)){state.map.setPaintProperty(layer.id,"fill-color","#deddd6");state.map.setPaintProperty(layer.id,"fill-opacity",.72);}if(layer.type==="fill"&&/(park|grass|wood|forest|landcover)/.test(id))state.map.setPaintProperty(layer.id,"fill-color","#dce9dc");if(layer.type==="line"&&/(road|street|motorway|trunk)/.test(id)){state.map.setPaintProperty(layer.id,"line-color",/motorway|trunk/.test(id)?"#e5c8ab":"#ffffff");state.map.setPaintProperty(layer.id,"line-opacity",.88);}}catch{}}
}

function initMap(){
  state.map=new maplibregl.Map({container:"map",style:"https://tiles.openfreemap.org/styles/liberty",center:[state.center.lon,state.center.lat],zoom:14.3,pitch:0,bearing:0,minZoom:7,maxZoom:19,maxBounds:[[120.72,24.30],[122.20,25.42]],dragRotate:false,touchPitch:false,fadeDuration:180,renderWorldCopies:false,attributionControl:true});
  state.map.on("styleimagemissing",e=>{if(!state.map.hasImage(e.id))state.map.addImage(e.id,{width:1,height:1,data:new Uint8Array([0,0,0,0])});});
  state.map.addControl(new maplibregl.NavigationControl({showCompass:false,visualizePitch:false}),"bottom-right");
  return new Promise(resolve=>state.map.on("load",()=>{state.mapReady=true;softenStyle();state.map.addSource("analysis-zone",{type:"geojson",data:{type:"FeatureCollection",features:[]}});state.map.addLayer({id:"analysis-fill",type:"fill",source:"analysis-zone",filter:["==",["geometry-type"],"Polygon"],paint:{"fill-color":"#2a8b67","fill-opacity":.11}});state.map.addLayer({id:"analysis-line",type:"line",source:"analysis-zone",filter:["==",["geometry-type"],"Polygon"],paint:{"line-color":"#176b4d","line-width":2.2,"line-dasharray":[2,1.4]}});state.map.addLayer({id:"site-halo",type:"circle",source:"analysis-zone",filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":18,"circle-color":"#176b4d","circle-opacity":.18,"circle-blur":.15}});state.map.addLayer({id:"site-point",type:"circle",source:"analysis-zone",filter:["==",["geometry-type"],"Point"],paint:{"circle-radius":9,"circle-color":"#17221d","circle-stroke-width":4,"circle-stroke-color":"#ffffff"}});bindMapEvents();resolve();}));
}

function addRegionLayers(id,places){
  const source=`poi-${id}`;if(state.map.getSource(source))return;
  state.map.addSource(source,{type:"geojson",data:featureCollection(places),cluster:true,clusterMaxZoom:16,clusterRadius:48,clusterMinPoints:3});
  state.map.addLayer({id:`cluster-halo-${id}`,type:"circle",source,filter:["has","point_count"],paint:{"circle-color":"rgba(23,107,77,.15)","circle-radius":["step",["get","point_count"],18,40,24,150,31,500,38],"circle-blur":.12}});
  state.map.addLayer({id:`cluster-${id}`,type:"circle",source,filter:["has","point_count"],paint:{"circle-color":["step",["get","point_count"],"#4c9b78",40,"#257858",150,"#176b4d",500,"#114f3a"],"circle-radius":["step",["get","point_count"],13,40,18,150,24,500,30],"circle-stroke-width":2,"circle-stroke-color":"rgba(255,255,255,.88)"}});
  state.map.addLayer({id:`cluster-count-${id}`,type:"symbol",source,filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-font":["Noto Sans Regular"],"text-size":["step",["get","point_count"],10,150,11]},paint:{"text-color":"#ffffff"}});
  state.map.addLayer({id:`points-${id}`,type:"circle",source,filter:["!",["has","point_count"]],paint:{"circle-color":colorExpression(),"circle-radius":["interpolate",["linear"],["zoom"],8,2,12,3.2,15,5.2,18,7],"circle-opacity":["interpolate",["linear"],["zoom"],8,.55,12,.72,15,.9],"circle-stroke-color":"rgba(255,255,255,.95)","circle-stroke-width":["interpolate",["linear"],["zoom"],10,.5,15,1.5]}});
}

async function ensureRegion(id,{quiet=false}={}){
  if(state.loaded.has(id)){state.currentRegion=id;updateRegionUI();return state.loaded.get(id);}
  const meta=regionMeta(id);if(!meta)return[];
  const cache=$("#map-cache");cache.classList.add("loading");cache.querySelector("span").textContent=`正在首次載入${meta.shortName}資料…`;
  const data=await fetch(meta.file).then(r=>{if(!r.ok)throw new Error(`${meta.name}資料載入失敗`);return r.json()});
  const places=data.places.map(p=>({id:`${id}:${p.id}`,region:id,name:p.n,brand:p.b,category:p.c,subcategory:p.s,cuisine:p.u,address:p.a,openingHours:p.h,lat:p.y,lon:p.x}));
  state.loaded.set(id,places);state.currentRegion=id;state.loadCount++;addRegionLayers(id,places);renderCategoryFilters();updateRegionUI();cache.classList.remove("loading");cache.querySelector("span").textContent=`${meta.shortName}資料已快取，縮放不重新載入`;
  if(!quiet)toast(`${meta.name} ${fmt.format(places.length)} 個點位已載入`);
  return places;
}

function updateRegionUI(){const meta=regionMeta(state.currentRegion);const loadedCount=allPlaces().length;$("#current-region").textContent=meta.shortName;$("#baseline-label").textContent=`${meta.name}區域資料`;$("#district-pop").textContent=compact.format(meta.count);$("#district-households").textContent=compact.format(loadedCount);$("#district-workforce").textContent=`${state.zoomReloads}次`;$("#data-status").textContent=`${fmt.format(state.regionIndex.totalCount)} 個北台灣開放點位 · 已快取 ${fmt.format(loadedCount)}`;$$('[data-region]').forEach(b=>b.classList.toggle("active",b.dataset.region===state.currentRegion));}

function bindMapEvents(){
  state.map.on("click",async e=>{const layers=[...state.loaded.keys()].flatMap(id=>[`points-${id}`,`cluster-${id}`]).filter(id=>state.map.getLayer(id));const hits=layers.length?state.map.queryRenderedFeatures(e.point,{layers}):[];const hit=hits[0];if(hit?.properties?.cluster){const source=state.map.getSource(hit.source);source.getClusterExpansionZoom(hit.properties.cluster_id).then(zoom=>state.map.easeTo({center:hit.geometry.coordinates,zoom,duration:520}));return;}if(hit){const p=hit.properties;new maplibregl.Popup({offset:10,maxWidth:"270px"}).setLngLat(hit.geometry.coordinates).setHTML(`<strong>${escapeHtml(p.n)}</strong><br><span class="popup-category">${escapeHtml(p.c)}</span>${p.u?`<br><small>口味：${escapeHtml(p.u)}</small>`:""}${p.a?`<br><small>${escapeHtml(p.a)}</small>`:""}`).addTo(state.map);return;}state.center={lat:e.lngLat.lat,lon:e.lngLat.lng};const meta=pointRegion(e.lngLat.lng,e.lngLat.lat);await ensureRegion(meta.id);state.address=`地圖選點 ${e.lngLat.lat.toFixed(5)}, ${e.lngLat.lng.toFixed(5)}`;$("#address-input").value=state.address;updateAnalysis({fit:false});});
  state.map.on("moveend",()=>{const c=state.map.getCenter(),meta=pointRegion(c.lng,c.lat);if(state.map.getZoom()>=10&&!state.loaded.has(meta.id))ensureRegion(meta.id,{quiet:true}).catch(()=>{});});
  state.map.on("mouseenter",()=>state.map.getCanvas().style.cursor="crosshair");
}

function updateAnalysisZone({fit=true}={}){const source=state.map.getSource("analysis-zone");if(!source)return;source.setData({type:"FeatureCollection",features:[circlePolygon(state.center,state.radius),{type:"Feature",properties:{},geometry:{type:"Point",coordinates:[state.center.lon,state.center.lat]}}]});if(fit){const d=state.radius/111000;state.map.fitBounds([[state.center.lon-d*1.25,state.center.lat-d],[state.center.lon+d*1.25,state.center.lat+d]],{padding:{top:110,bottom:55,left:55,right:55},duration:650,maxZoom:18});}}

function analyze(){const nearby=allPlaces().filter(p=>distanceMeters(state.center,p)<=state.radius);state.nearby=nearby;const counts=Object.fromEntries(groupCount(nearby,p=>p.category)),total=nearby.length,areaHa=Math.PI*state.radius**2/10000,uniqueBrands=new Set(nearby.map(p=>p.brand).filter(Boolean)),named=nearby.filter(p=>!p.name.startsWith("未命名")),diversity=Object.keys(counts).length/Object.keys(CATEGORY_META).length,office=counts["公司辦公"]||0,transit=counts["交通節點"]||0,restaurants=counts["餐飲"]||0,drinks=counts["飲料咖啡"]||0,convenience=counts["便利零售"]||0,medical=counts["醫療健康"]||0,leisure=(counts["運動娛樂"]||0)+(counts["觀光休閒"]||0),education=counts["教育學習"]||0,density=total/Math.max(areaHa,.01),officeIntensity=clamp(office/Math.max(areaHa,1),0,8),spendIndex=Math.round(clamp(94+officeIntensity*3+medical*.24+uniqueBrands.size*.17+transit*1.5,82,142)),lunchFlow=Math.round(clamp(office*19+restaurants*11+drinks*6+transit*150+convenience*8+education*13,90,24500)),weekendRatio=clamp(.45+(leisure+convenience+medical)/Math.max(20,office+restaurants)*.35,.35,1.05),demand=Math.round(clamp(42+Math.log1p(density)*10+officeIntensity*2.5,30,96)),access=Math.round(clamp(45+transit*7+convenience*.8+Math.min(state.radius/80,9),35,96)),complement=Math.round(clamp(48+diversity*48+Math.min(convenience+medical+education,18),35,95)),spending=Math.round(clamp((spendIndex-75)*1.35,35,95)),competition=Math.round(clamp(90-(restaurants+drinks)/Math.max(total,1)*95+diversity*15,35,93)),resilience=Math.round(clamp(42+weekendRatio*40+leisure*1.1,35,93)),score=Math.round(demand*.24+access*.17+complement*.14+spending*.18+competition*.12+resilience*.15),confidence=Math.round(clamp(58+Math.log1p(total)*5+named.length/Math.max(total,1)*12,58,92));return{counts,total,areaHa,uniqueBrands,named,density,office,transit,restaurants,drinks,convenience,medical,leisure,education,diversity,spendIndex,lunchFlow,weekendRatio,score,confidence,components:{demand,access,complement,spending,competition,resilience}};}

function renderCategoryFilters(){const totals=Object.fromEntries(groupCount(allPlaces(),p=>p.category));const visible=Object.entries(CATEGORY_META).filter(([n])=>totals[n]).sort((a,b)=>(totals[b[0]]||0)-(totals[a[0]]||0));$("#category-filters").innerHTML=visible.map(([n,m])=>`<button class="filter-chip ${state.filters.get(n)?"":"off"}" data-category="${n}" style="--chip:${m.color}"><span class="swatch"></span><span>${n}</span><span class="filter-count">${fmt.format(totals[n]||0)}</span></button>`).join("");}
function renderCategoryBars(a){const entries=Object.entries(a.counts).sort((x,y)=>y[1]-x[1]).slice(0,6),max=entries[0]?.[1]||1;$("#category-bars").innerHTML=entries.length?entries.map(([n,c])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="--width:${c/max*100}%;--bar:${CATEGORY_META[n]?.color||"#718078"}"></div></div><b>${c}</b></div>`).join(""):`<p class="method-note" style="margin:0">此半徑尚無已收錄點位，請放大範圍。</p>`;}
function opportunityModel(a){const per100=n=>(a.counts[n]||0)/Math.max(a.total,1)*100;return[{name:"健康快速午餐",score:88+a.office*.18-per100("餐飲")*1.7,why:"辦公需求高、重視速度與可預期品質"},{name:"精品咖啡／會議外送",score:78+a.office*.2-per100("飲料咖啡")*2.1,why:"商務會議與下午提神場景可疊加"},{name:"晚間社區型餐飲",score:64+a.convenience*.8+a.medical*.5-a.office*.08,why:"補足商辦區晚間流量下滑"},{name:"運動恢復／輕健身",score:61+a.office*.12-a.leisure*2.5,why:"下班時段與久坐族需求互補"},{name:"親子生活服務",score:54+a.education*1.7+a.convenience-a.office*.04,why:"住宅與學校密度帶動固定回訪"}].map(x=>({...x,score:Math.round(clamp(x.score,38,96))})).sort((x,y)=>y.score-x.score).slice(0,3);}
function renderOpportunities(a){$("#opportunity-list").innerHTML=opportunityModel(a).map((x,i)=>`<div class="opportunity"><span class="opportunity-rank">0${i+1}</span><div><strong>${x.name}</strong><span>${x.why}</span></div><span class="opportunity-score">${x.score}</span></div>`).join("");}
function renderCategoryTable(a){$("#category-table").innerHTML=Object.entries(a.counts).sort((x,y)=>y[1]-x[1]).slice(0,12).map(([n,c])=>{const d=c/Math.max(a.areaHa,.1),l=d>2.2?["高","high"]:d>.8?["中","medium"]:["低","low"],t=CATEGORY_META[n]?.ticket||0;return`<div class="table-row"><span class="cat-name">${n}</span><b>${c}</b><span>${t?`$${fmt.format(t)}`:"—"}</span><span class="comp-level ${l[1]}">${l[0]}</span></div>`}).join("")||`<div class="table-row"><span>無已收錄店家</span></div>`;}
function renderCuisine(){const cuisines=groupCount(state.nearby.flatMap(p=>(p.cuisine||"").split(/[;,]/).filter(Boolean).map(c=>({c:c.trim()}))),x=>x.c);$("#cuisine-tags").innerHTML=cuisines.length?cuisines.slice(0,14).map(([n,c])=>`<span>${CUISINE_NAMES[n]||n}<b>${c}</b></span>`).join(""):`<span>未標註口味</span>`;}
function renderPeople(a){const officeLed=a.office>a.convenience+a.education,residential=a.convenience+a.medical+a.education>a.office*.7;$("#persona-title").textContent=officeLed?"效率型科技上班族":residential?"穩定回訪的家庭住戶":"通勤與生活混合客群";$("#persona-copy").textContent=officeLed?"重視出餐速度、可預期品質與行動支付；午餐決策半徑短，平日下午有咖啡與飲品需求。":residential?"重視便利、信任與固定回訪；晚餐、醫療與日常採買比午間單一尖峰更穩定。":"平日通勤需求與在地生活消費並存，可用早餐、午餐與晚間服務分散單一時段風險。";$("#persona-chips").innerHTML=(officeLed?["25–44 歲核心","重視效率","行動支付","外送接受度高"]:["家庭採買","熟客關係","晚間需求","週末仍有流量"]).map(x=>`<span>${x}</span>`).join("");const base=state.stats.ageBands,boost=clamp(a.office/Math.max(a.total,1)*1.8,0,.5),f=[1,.8,1+boost,1.18+boost,1.06+boost*.5,.88,.8],adj=base.map((x,i)=>({label:x.label,value:x.value*f[i]})),sum=adj.reduce((s,x)=>s+x.value,0),ages=adj.map(x=>({label:x.label,pct:x.value/sum*100})),max=Math.max(...ages.map(x=>x.pct));$("#age-chart").innerHTML=ages.map(x=>`<div class="age-bar" style="--height:${x.pct/max*100}%"><i></i><b>${x.pct.toFixed(0)}%</b><span>${x.label}</span></div>`).join("");}
function renderFlow(a){const of=clamp(a.office/Math.max(a.areaHa,1),0,10),rf=clamp((a.convenience+a.medical+a.education)/Math.max(a.areaHa,1),0,9),raw=[.12+rf*.008,.18,.48+of*.025,.72+of*.02,.46,.58,1,.78,.53,.49,.62+of*.015,.83+of*.015,.71,.49+rf*.018,.35+rf*.02,.2],flow=raw.map((v,i)=>({hour:i+6,value:Math.round(a.lunchFlow*clamp(v,.12,1.08))})),max=Math.max(...flow.map(x=>x.value));$("#flow-chart").innerHTML=flow.map(x=>`<div class="flow-column ${x.value>max*.82?"peak":""}" style="--height:${x.value/max*100}%"><i></i>${x.hour%2===0?`<span>${x.hour}</span>`:""}</div>`).join("");const events=[["08:00","通勤進場",flow.find(x=>x.hour===8).value],["12:00","午餐尖峰",flow.find(x=>x.hour===12).value],["18:00","下班移動",flow.find(x=>x.hour===18).value]];$("#flow-events").innerHTML=events.map(x=>`<div class="flow-event"><time>${x[0]}</time><div><strong>${x[1]}</strong><span>周邊業態加權推估</span></div><b>${compact.format(x[2])}</b></div>`).join("");const w=Math.round(a.weekendRatio*100);$("#day-compare").innerHTML=`<div class="day-row"><span>平日</span><div class="day-track"><div class="day-fill" style="--width:100%"></div></div><b>100</b></div><div class="day-row weekend"><span>假日</span><div class="day-track"><div class="day-fill" style="--width:${w}%"></div></div><b>${w}</b></div>`;}
function renderAdvice(a){const labels={demand:"需求密度",access:"交通可達",complement:"業態互補",spending:"消費能力",competition:"競爭餘裕",resilience:"時段韌性"};$("#score-breakdown").innerHTML=Object.entries(a.components).map(([k,v])=>`<div class="score-line ${v<55?"low":""}"><span>${labels[k]}</span><div class="line-track"><i style="--width:${v}%"></i></div><b>${v}</b></div>`).join("");const top=opportunityModel(a)[0],items=[["good","+",`優先測試「${top.name}」`,`${top.why}；建議先以快閃或外送熱區驗證。`],[a.weekendRatio<.62?"warn":"good",a.weekendRatio<.62?"!":"+",a.weekendRatio<.62?"控制週末固定成本":"週間流量較均衡",a.weekendRatio<.62?"商辦型商圈假日落差較大，排班與營業時間要能縮放。":"生活服務與休閒設施可降低只靠平日午餐的風險。"],["good","✓","簽約前做 3 日現場計數","至少觀察週二、週五與週六的 08:00、12:00、18:00，每次 30 分鐘。"]];$("#advice-list").innerHTML=items.map(x=>`<div class="advice-item ${x[0]}"><span class="advice-icon">${x[1]}</span><div><strong>${x[2]}</strong><p>${x[3]}</p></div></div>`).join("");}
function renderSummary(a){$("#selected-address").textContent=state.address;$("#site-score").textContent=a.score;$("#score-ring").style.setProperty("--score",a.score);$("#confidence-score").textContent=`${a.confidence}%`;$("#poi-count").textContent=fmt.format(a.total);$("#poi-density").textContent=`${a.density.toFixed(1)} 家／公頃`;$("#brand-count").textContent=fmt.format(a.uniqueBrands.size);$("#brand-ratio").textContent=`連鎖辨識率 ${Math.round(a.uniqueBrands.size/Math.max(a.total,1)*100)}%`;$("#spend-index").textContent=a.spendIndex;$("#lunch-flow").textContent=compact.format(a.lunchFlow);const good=a.score>=72;$("#verdict").classList.toggle("caution",!good);$("#verdict").innerHTML=`<span class="verdict-icon">${good?"↗":"!"}</span><div><strong>${good?"值得進一步評估":"條件式可行"}</strong><p>${a.office>a.convenience?"午間剛需強，晚間與假日需靠目的型消費補足。":"生活型需求較穩定，仍需核對租金與街邊可見度。"}</p></div>`;}
function renderAll(a){state.analysis=a;renderSummary(a);renderCategoryBars(a);renderOpportunities(a);renderCategoryTable(a);renderCuisine();renderPeople(a);renderFlow(a);renderAdvice(a);renderCategoryFilters();}
function updateAnalysis(options={}){const a=analyze();renderAll(a);updateAnalysisZone(options);$("#walk-time").textContent=`${Math.max(1,Math.round(state.radius/80))} 分鐘`;}

async function geocodeAddress(address){const normalized=(address.includes("台")||address.includes("臺")?address:`${regionMeta(state.currentRegion).name} ${address}`).replace(/^台北/,"臺北"),lookup=async q=>{const u=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=tw&accept-language=zh-TW&q=${encodeURIComponent(q)}`,r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error("地址服務暫時無法使用");return r.json()};let data=await lookup(normalized);if(!data.length){const f=normalized.replace(/\d+弄.*$/,"").replace(/\d+號.*$/,"");if(f!==normalized){await new Promise(r=>setTimeout(r,1050));data=await lookup(f);}}if(!data.length)throw new Error("找不到這個地址，請改用附近路名或直接點地圖");const lat=Number(data[0].lat),lon=Number(data[0].lon),id=labelRegion(data[0].display_name)||pointRegion(lon,lat)?.id;if(!id||lon<120.72||lon>122.2||lat<24.3||lat>25.42)throw new Error("目前支援台北、新北、基隆、桃園與新竹");return{lat,lon,id,label:data[0].display_name};}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400);}
function renderSources(){$("#sources-list").innerHTML=state.sources.map(s=>`<div class="source-row"><div><strong>${s.name}</strong><p>${s.owner} · ${s.frequency} · 用於${s.usage}</p><a href="${s.url}" target="_blank" rel="noopener">開啟原始資料 ↗</a></div><span class="source-badge ${s.kind==="官方統計"?"official":s.kind==="實際觀測"?"observed":"model"}">${s.kind}</span></div>`).join("");}

function applyCategoryFilter(){const active=[...state.filters].filter(([,v])=>v).map(([k])=>k),filter=["all",["!",["has","point_count"]],["in",["get","c"],["literal",active]]];for(const id of state.loaded.keys())if(state.map.getLayer(`points-${id}`))state.map.setFilter(`points-${id}`,filter);}
function bindEvents(){
  $("#address-form").addEventListener("submit",async e=>{e.preventDefault();const address=$("#address-input").value.trim();if(!address)return;const b=e.currentTarget.querySelector("button");b.textContent="…";try{const r=await geocodeAddress(address);state.center={lat:r.lat,lon:r.lon};state.address=address;await ensureRegion(r.id);updateAnalysis();toast("已完成地址周邊分析");}catch(err){toast(err.message)}finally{b.textContent="→"}});
  $(".quick-addresses").addEventListener("click",async e=>{const b=e.target.closest("button[data-region]");if(!b)return;state.center={lat:Number(b.dataset.lat),lon:Number(b.dataset.lon)};state.address=b.dataset.address;$("#address-input").value=state.address;await ensureRegion(b.dataset.region);updateAnalysis();});
  $(".radius-options").addEventListener("click",e=>{const b=e.target.closest("button[data-radius]");if(!b)return;state.radius=Number(b.dataset.radius);$$('.radius-options button').forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-checked",x===b?"true":"false")});updateAnalysis();});
  $("#category-filters").addEventListener("click",e=>{const b=e.target.closest("button[data-category]");if(!b)return;state.filters.set(b.dataset.category,!state.filters.get(b.dataset.category));renderCategoryFilters();applyCategoryFilter();});
  $("#toggle-all").addEventListener("click",e=>{const on=[...state.filters.values()].some(Boolean);state.filters.forEach((_,k)=>state.filters.set(k,!on));e.currentTarget.textContent=on?"全部顯示":"全部隱藏";renderCategoryFilters();applyCategoryFilter();});
  $(".tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-tab]");if(!b)return;$$('.tabs button').forEach(x=>x.classList.toggle("active",x===b));$$('.tab-panel').forEach(x=>x.classList.toggle("active",x.id===`tab-${b.dataset.tab}`));});
  $("#reset-view").addEventListener("click",()=>updateAnalysisZone({fit:true}));
  $("#locate-button").addEventListener("click",()=>{if(!navigator.geolocation)return toast("此瀏覽器不支援定位");navigator.geolocation.getCurrentPosition(async p=>{state.center={lat:p.coords.latitude,lon:p.coords.longitude};const r=pointRegion(state.center.lon,state.center.lat);await ensureRegion(r.id);state.address="目前位置";$("#address-input").value=state.address;updateAnalysis();},()=>toast("無法取得目前位置，請改用地址或地圖選點"));});
  const sd=$("#sources-dialog"),hd=$("#help-dialog");$("#open-sources").addEventListener("click",()=>sd.showModal());$("#help-button").addEventListener("click",()=>hd.showModal());$$('dialog .dialog-close').forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$$('dialog').forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));
  $("#export-button").addEventListener("click",()=>{const a=state.analysis,report={product:"北台灣開店雷達",generatedAt:new Date().toISOString(),region:regionMeta(state.currentRegion).name,address:state.address,coordinates:state.center,radiusMeters:state.radius,score:a.score,confidence:a.confidence,nearbyBusinesses:a.total,brandCount:a.uniqueBrands.size,spendingIndex:a.spendIndex,estimatedLunchFlow:a.lunchFlow,categories:a.counts,opportunities:opportunityModel(a),disclaimer:"模型初篩，不構成營收或投資保證。"},blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json;charset=utf-8"}),u=URL.createObjectURL(blob),link=document.createElement("a");link.href=u;link.download=`北台灣開店雷達-${state.radius}m-分析.json`;link.click();URL.revokeObjectURL(u);toast("分析摘要已匯出")});
}

async function boot(){try{const [index,stats,sources]=await Promise.all([fetch("./data/regions/index.json").then(r=>r.json()),fetch("./data/neihu-stats.json").then(r=>r.json()),fetch("./data/sources.json").then(r=>r.json())]);state.regionIndex=index;state.stats=stats;state.sources=sources;await initMap();await ensureRegion("taipei",{quiet:true});renderSources();bindEvents();updateAnalysis();}catch(err){console.error(err);$("#data-status").textContent="資料載入失敗";toast(`載入失敗：${err.message}`);}}
boot();
